S.E.A INTERVALLO 4.5 ПРАВЛЕННЫЙ ПЕРЕВОД #2 EBLAN EDITION
kimght/LimbusStory pull request #5
Opened 2024-08-28 20:48 UTC by DAFTPUSiK

### - Исправлены склонения и орфографические ошибки.
### - ВАРП был заменен на WARP.
### - Заменено уменьшительно-ласкательное Измаил - Изя.

2024-08-28 20:51 UTC, DAFTPUSiK reviewed
Поменял термины на соответствующие другим Канто, поменял очевидно значение определенных слов на те, которые имелись ввиду? И вроде всё.

2024-08-29 08:38 UTC, kimght requested changes
Здорово, но в паре мест я бы поправил. Посмотри где я комментарии написал

2024-08-29 08:38 UTC, kimght commented on chapters/E402A.txt
> +Измаил: Крабы-мусорщики. Они собирают на своих панцирях мусор и обломки, используя их как дома и орудия.
Думаю, оригинальный вариант подходит лучше

2024-08-29 08:38 UTC, kimght commented on chapters/E403B.txt
> +Мерсо: Похоже, они того же вида, что и тот, с которыми мы столкнулись ранее.
Либо
>Похоже, они того же вида, что и тот, с которым мы столкнулись ранее.

Либо
>Похоже, они того же вида, что и те, с которыми мы столкнулись ранее.

2024-08-29 08:38 UTC, kimght commented on chapters/E403B.txt
> +Вергилий: ...Полагаю, внезапная смена карьеры далась нелегко. Можно ли с этим справиться...
Формулировка так себе. Может было бы лучше что-то типа:
>Справились ли вы с этим...

Но хз

2024-08-29 08:38 UTC, kimght commented on chapters/E403B.txt
> +Вергилий: Похоже, что люди возвращаются один за другим из книг после инцидента в "Библиотеке".
Может быть
>Похоже, что люди постепенно возвращаются из книг после инцидента в "Библиотеке".

2024-08-29 08:38 UTC, kimght commented on chapters/E403B.txt
> +Мика: Весь транспорт.
>Ольга: Ну и сколько нам придётся над ним работать?
>Мика: Весь транспорт.

Не звучит. Но как лучше не знаю. Может стоит фразу Ольги переделать, чтобы она лучше стыковалась с ответом.

2024-08-29 08:38 UTC, kimght commented on chapters/E404B.txt
> +Хитклиф: Это ещё что за отношение такое? Если Аномалия проломит мне череп, поверни часы назад, и в следующий раз я дам ей сломать мне ногу. Мы можем возвращаться снова и снова, пока они не разнесутся
Тогда уж так:
>...пока не разнесём их на куски

2024-08-29 08:38 UTC, kimght commented on chapters/E406B.txt
> +Вергилий: В конце концов, эти... нянченье и воспитания - не часть моей работы, менеджер Данте.
Тогда лучше уж целиком переделать?
>это... нянченье и воспитание

или
>В конце концов... нянченье и воспитание - не часть моей работы, менеджер Данте.

2024-08-29 08:38 UTC, kimght commented on chapters/E406B.txt
> +Рассказчик: Она не игнорировала меня. Скорее... слишком глубоко погрузилась в чем занималась.
"то" пропустил

2024-08-29 08:38 UTC, kimght commented on chapters/E407B.txt
> +Измаил: Мы все подписали контракт с Компанией Лимбус ради собственных целей. Я подписала, И Сан тоже, как мы видели в прошлый раз, и все остальные Грешники.
Хз, оригинал мне больше нравится

2024-08-29 08:38 UTC, kimght commented on chapters/E405B.txt
> +Дон Кихот: И будет совсем не пустою хвальбою сказать, что лишать себя забавы, когда шар, красивые люди и пляж всё ждут нас - сущая несправедливость!
Я бы оставил как есть, максимум заменил "годные" на "способные".

2024-08-29 08:38 UTC, kimght commented on chapters/E405B.txt
> +И Сан: Не могу похвастаться особыми талантами в играх с мячом... но, видимо, сейчас самый подходящий момент, чтобы впервые испытать это.
Тут хорошо перевело, менять не надо

2024-08-29 09:07 UTC, DAFTPUSiK commented on chapters/E402A.txt
> +Измаил: Крабы-мусорщики. Они собирают на своих панцирях мусор и обломки, используя их как дома и орудия.
Принято

2024-08-29 09:08 UTC, DAFTPUSiK commented on chapters/E403B.txt
> +Мерсо: Похоже, они того же вида, что и тот, с которыми мы столкнулись ранее.
Принято

2024-08-29 09:09 UTC, DAFTPUSiK commented on chapters/E403B.txt
> +Вергилий: ...Полагаю, внезапная смена карьеры далась нелегко. Можно ли с этим справиться...
Принято

2024-08-29 09:24 UTC, DAFTPUSiK commented on chapters/E406B.txt
> +Рассказчик: Она не игнорировала меня. Скорее... слишком глубоко погрузилась в чем занималась.
Принято

2024-08-29 09:27 UTC, DAFTPUSiK commented on chapters/E407B.txt
> +Измаил: Мы все подписали контракт с Компанией Лимбус ради собственных целей. Я подписала, И Сан тоже, как мы видели в прошлый раз, и все остальные Грешники.
### В грамматике "did", подразумевается как смысловой глагол. То есть какое то действие, в контексте предложения имеется ввиду, "Подписывание". В изначальном переводе теряется смысл, ибо она говорит "Мы все подписали контракт", а после Я, И Сан, и т.д. Она не уточняет конкретно. А в оригинале предполагается именно действие. Ну и банально, так будет более очевидно, что она имеет ввиду.

2024-08-29 09:29 UTC, DAFTPUSiK commented on chapters/E405B.txt
> +Дон Кихот: И будет совсем не пустою хвальбою сказать, что лишать себя забавы, когда шар, красивые люди и пляж всё ждут нас - сущая несправедливость!
Поменял на "Красивые" на "Здоровые". Все таки пляж, и имеется ввиду здоровый отдых или в таком духе, хз.

2024-08-29 09:30 UTC, DAFTPUSiK commented on chapters/E405B.txt
> +И Сан: Не могу похвастаться особыми талантами в играх с мячом... но, видимо, сейчас самый подходящий момент, чтобы впервые испытать это.
Принято

2024-08-29 09:51 UTC, kimght approved these changes
Пойдет

2024-08-29 09:51 UTC, merged