CANTO IV ПРАВЛЕННЫЙ ПЕРЕВОД
kimght/LimbusStory pull request #6
Opened 2024-08-30 23:54 UTC by DAFTPUSiK

### - Исправлены склонения и орфографические ошибки.
### - Исправлены построения предложений.
### - Машинные идиомы заменены на более понятные.

2024-08-30 23:55 UTC, DAFTPUSiK commented
пиздец там текста, пойду спать

2024-08-31 12:16 UTC, DAFTPUSiK reviewed
### - Поправил свои орфографические ошибки.
### - Исправил смысловые ошибки в предложениях.

2024-08-31 19:29 UTC, kimght requested changes
Написал что поправить

2024-08-31 19:29 UTC, kimght commented on chapters/4D107B.txt
> +Измаил: ...Помнишь? Первое, что я изобрела... после того, как устроилась на работу в Крыло Корпорации T.
Просто в Корпорацию Т, или в Крыло Т

2024-08-31 19:29 UTC, kimght commented on chapters/4D107B.txt
> +И Сан: Вот такие достижения мы совершали в районе Крыла Корпорации T.
Тут тоже

2024-08-31 19:29 UTC, kimght commented on chapters/4D202B.txt
> +Родион: Я выкроила драгоценное время в своем плотном графике, чтобы посмотреть, какой была группа с Ён-джи... а вижу только детские игрушки.
>какой была группа Ён-джи

2024-08-31 19:29 UTC, kimght commented on chapters/4D204B.txt
> +Отис: Мы получили официальное уведомление о том, что частные группы технологических изобретателей из пяти или более человек, не зарегистрированные как предприятие, требуют разрешения от Крыла Корпора
И тут

2024-08-31 19:29 UTC, kimght commented on chapters/4D204B.txt
> +Донран: Подождите, подождите. Эта идея о том, что мы должны создавать технологии тайно, может быть ловушкой, понимаете? Кто знает, может Крыло Корпорации Т просто даст нам одобрение.
И тут

2024-08-31 19:29 UTC, kimght commented on chapters/4D204B.txt
> +Донран: Давайте посмотрим на общую картину. Разве не выиграет ли от них Город в целом, а не только Крыло Корпорации Т?
И тут

2024-08-31 19:29 UTC, kimght commented on chapters/4D302B.txt
> +Мерсо: Что наводит на мысль о том, что это чужеродная субстанция, пытающаяся проникнуть в глубины эго.
фантомов эго

2024-08-31 19:29 UTC, kimght commented on chapters/S412B.txt
> +Грегор: Разве это не отвратительно... Думаете, можно устраивать показательные казни, когда даже не идёт войны?
Как-то криво звучит, я бы заменил на
>даже в мирное время

2024-08-31 19:29 UTC, kimght commented on chapters/S415B.txt
> +И Сан: Почему же тогда Крыло Корпорации... не оказывает помощи?
Опять крыло корпорации

2024-08-31 19:29 UTC, kimght commented on chapters/S415B.txt
> +Донран: Например, фотографию в честь моей третьей подряд победы в конкурсе за выдающиеся достижения, благодарственную табличку от Крыла Корпорации К, фотографию, сделанную в честь расширения моей лаб
Опять крыло корпорации

2024-08-31 19:29 UTC, kimght commented on chapters/S422B.txt
> +Родион: Прошу тебя. Ты же не думаешь, что только ты помнишь то логово жуков, правда, Грег милый?
Запятая

2024-08-31 19:29 UTC, kimght commented on chapters/S433A.txt
> +Фауст: То, что они используют — это инструменты, сжатые и сдавленные для общего применения.
Разве? В оригинале вроде правильно

2024-08-31 19:34 UTC, DAFTPUSiK commented on chapters/4D102A.txt
> +И Сан: Брат Ён-джи был добрым человеком. Он не был склонен необдуманно таить злобу или упрёков к другим.
Принято

2024-08-31 19:35 UTC, DAFTPUSiK commented on chapters/4D107B.txt
> +Измаил: ...Помнишь? Первое, что я изобрела... после того, как устроилась на работу в Крыло Корпорации T.
Принято

2024-08-31 19:37 UTC, DAFTPUSiK commented on chapters/4D107B.txt
> +И Сан: Вот такие достижения мы совершали в районе Крыла Корпорации T.
Принято

2024-08-31 19:38 UTC, DAFTPUSiK commented on chapters/4D202B.txt
> +Родион: Я выкроила драгоценное время в своем плотном графике, чтобы посмотреть, какой была группа с Ён-джи... а вижу только детские игрушки.
Принято

2024-08-31 19:39 UTC, DAFTPUSiK commented on chapters/4D204B.txt
> +Отис: Мы получили официальное уведомление о том, что частные группы технологических изобретателей из пяти или более человек, не зарегистрированные как предприятие, требуют разрешения от Крыла Корпора
Принято

2024-08-31 19:40 UTC, DAFTPUSiK commented on chapters/4D204B.txt
> +Донран: Давайте посмотрим на общую картину. Разве не выиграет ли от них Город в целом, а не только Крыло Корпорации Т?
Принято

2024-08-31 19:40 UTC, DAFTPUSiK commented on chapters/4D204B.txt
> +Донран: Подождите, подождите. Эта идея о том, что мы должны создавать технологии тайно, может быть ловушкой, понимаете? Кто знает, может Крыло Корпорации Т просто даст нам одобрение.
Принято

2024-08-31 19:45 UTC, DAFTPUSiK commented on chapters/S415B.txt
> +И Сан: Почему же тогда Крыло Корпорации... не оказывает помощи?
Принято

2024-08-31 19:46 UTC, DAFTPUSiK commented on chapters/S422B.txt
> +Родион: Прошу тебя. Ты же не думаешь, что только ты помнишь то логово жуков, правда, Грег милый?
Принято

2024-08-31 19:46 UTC, DAFTPUSiK commented on chapters/S415B.txt
> +Донран: Например, фотографию в честь моей третьей подряд победы в конкурсе за выдающиеся достижения, благодарственную табличку от Крыла Корпорации К, фотографию, сделанную в честь расширения моей лаб
Принято

2024-08-31 19:49 UTC, DAFTPUSiK commented on chapters/S433A.txt
> +Фауст: То, что они используют — это инструменты, сжатые и сдавленные для общего применения.
Исправил

2024-09-01 08:20 UTC, kimght approved these changes
Принято

2024-09-01 08:21 UTC, merged