CANTO V ПРАВЛЕННЫЙ ПЕРЕВОД (микрофикс 4.0-4.5)
kimght/LimbusStory pull request #7
Opened 2024-09-26 16:08 UTC by DAFTPUSiK

### - Исправлены склонения и орфографические ошибки.
### - Исправлены построения предложений.
### - Машинные идиомы заменены на более понятные.
### - Исправлены ошибки в 4 Песни, и в Антракте 4.5.

2024-09-28 09:32 UTC, DAFTPUSiK reviewed
### - Исправил орфографию.
### - Удалил не нужный текст.

2024-10-03 08:32 UTC, kimght requested changes

2024-10-03 08:32 UTC, kimght commented on chapters/5D106B.txt
> +Ахав: Помогите мне в моём плане. Мы убьём этого Кита после охоты и сбежим, а Золотая Ветвь будет вашей.
Странно звучит, лучше убрать охоту или как-то перефразировать

2024-10-03 08:32 UTC, kimght commented on chapters/5D107B.txt
> +Рассказчик: Когда мы сражались с Китом и его вырождениями, которые пришли с Волнами...
порождениями?

2024-10-03 08:32 UTC, kimght commented on chapters/5D202A.txt
> +Измаил: Когда мы уничтожим сердце, и когда я собственными руками выдавлю жизнь из Ахава...
Ахав звучит лучше?

2024-10-03 08:32 UTC, kimght commented on chapters/5D203B.txt
> +Хитклиф: Она же вся в крови измазана. Теперь у тебя прям жуткий вид, а?
Ободок - он

2024-10-03 08:32 UTC, kimght commented on chapters/5D203B.txt
> +Измаил: Но суть в том, что Китовое масло покрывает и поглощает всех, с кем соприкасается.
Надо будет потом поменять масло на жир

2024-10-03 08:32 UTC, kimght commented on chapters/5D206B.txt
> +Рассказчик: Приказы Ахава вели нас прямо к её единственной цели – сердцу.
Ахав?

2024-10-03 08:32 UTC, kimght commented on chapters/5D304A.txt
> +Отис: Старший помощник Измаил.
Первый помощник

2024-10-03 08:32 UTC, kimght commented on chapters/5D304I3.txt
> +Ахав: Старбак был первым, кто преклонил колени. Неважно, сколько штормов пережил старший помощник... Место старшего помощника всё равно ниже, чем у его Капитана...!
Первый помощник

2024-10-03 08:32 UTC, kimght commented on chapters/5D304I8.txt
> +Измаил: Когда-то, Я была твоей Русалкой. Поглощённая и переписанная твоими убеждениями, я плыла к возвышающемуся безумному Киту, у которого было твое лицо.
`Я` маленькая

2024-10-03 08:32 UTC, kimght commented on chapters/S502B.txt
> +Фауст: У Великого Озера Корпорации U. есть законы, которые... никогда не должны нарушаться.
Лишняя точка после U

2024-10-03 08:32 UTC, kimght commented on chapters/S510B.txt
> +Сми: Да. Я Сми, старший помощник Пиратов-Двукрюков.
Первый

2024-10-03 09:05 UTC, DAFTPUSiK commented on chapters/5D106B.txt
> +Измаил: Старбак... старший помощник Пекода.
Старший Помощник по идее более правильным будет, ибо в книге упомянается, как Старший. У Вкшек тоже Старший, да и в целом на флоте звания делятся на старших и младших. Есть только Капитаны разных рангов. Я вот по этому поводу тоже думал, может Стабба тогда младшим помощником записать.

2024-10-03 09:05 UTC, DAFTPUSiK commented on chapters/5D106B.txt
> +Ахав: Помогите мне в моём плане. Мы убьём этого Кита после охоты и сбежим, а Золотая Ветвь будет вашей.
Принято

2024-10-03 09:08 UTC, DAFTPUSiK commented on chapters/5D107B.txt
> +Рассказчик: Когда мы сражались с Китом и его вырождениями, которые пришли с Волнами...
Принято.

2024-10-03 09:08 UTC, DAFTPUSiK commented on chapters/5D203B.txt
> +Хитклиф: Она же вся в крови измазана. Теперь у тебя прям жуткий вид, а?
Принято.

2024-10-03 09:09 UTC, DAFTPUSiK commented on chapters/5D203B.txt
> +Измаил: Но суть в том, что Китовое масло покрывает и поглощает всех, с кем соприкасается.
жыбий рыр

2024-10-03 09:09 UTC, DAFTPUSiK commented on chapters/5D304I8.txt
> +Измаил: Когда-то, Я была твоей Русалкой. Поглощённая и переписанная твоими убеждениями, я плыла к возвышающемуся безумному Киту, у которого было твое лицо.
Принято

2024-10-03 09:10 UTC, DAFTPUSiK commented on chapters/S502B.txt
> +Фауст: У Великого Озера Корпорации U. есть законы, которые... никогда не должны нарушаться.
Принято.

2024-10-03 14:50 UTC, DAFTPUSiK reviewed
### Ахав больше не склоняется.

2024-10-03 19:06 UTC, kimght approved these changes
Малаца!

2024-10-03 19:15 UTC, merged